# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog
tagline:             'A personal blog about nothing and all'
description:         'Dunno yet...'
url:                 http://trahn.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Till Rahn
  url:               http://www.tillrahn.com
  email:             till.rahn@gmail.com

# Custom vars
version:             1.0.0
