# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Till Rahn'
tagline:             'A personal blog about nothing and all'
description:         'Whatever.'
url:                 http://tillrahn.com
baseurl:			 /
paginate:            5

# About/contact
author:
  name:              Till Rahn
  url:               http://tillrahn.com
  email:             till.rahn@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jemoji
