# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Till Rahn'
tagline:             'A personal blog about everything and nothing'
description:         'This blog contains thoughts and topics close to me. It serves as a personal reflection space and accompanies me during whatever I am currently pursuing.'
url:                 http://tillrahn.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Till Rahn
  url:               http://tillrahn.com
  email:             till.rahn@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jemoji
