# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'A personal blog about anything and everything'
description:      'Dunno yet.'
url:              http://trahn.github.io

author:
  name:           'Till Rahn'
  url:            http://www.tillrahn.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
